version: '3.4'

services:
  sqldata:
    image:  mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Irakl7881$
      - ACCEPT_EULA=Y
    ports:
      - "1450:1433"
  rentcarproject.api:
    image: ${DOCKER_REGISTRY-}rentcarprojectapi
    build:
      context: .
      dockerfile: RentCarProject.Api/Dockerfile
